version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - .docker/php.ini:/usr/local/etc/php/php.ini
      - .docker/apache-vhost.conf:/etc/apache2/sites-available/custom-vhost.conf
    container_name: cd_app
    env_file:
      - .docker/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    ports:
        - '3306:3306'
    volumes:
        - .docker/mysql/data:/var/lib/mysql
    restart: always
    env_file:
      - .docker/.env
    container_name: cd_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8010:80'
    env_file:
      - .docker/.env

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8020:8025'

  node:
    image: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - '8030:8081'
    command: npm run build:dev
    container_name: cd_node
